$Script:ResourceMap = @{
    # Circuits
    CircuitTermination        = 'circuits/circuit-terminations'
    CircuitType               = 'circuits/circuit-types'
    Circuit                   = 'circuits/circuits'
    CircuitGroup              = 'circuits/circuit-groups'
    CircuitGroupAssignment    = 'circuits/circuit-group-assignments'
    Provider                  = 'circuits/providers'
    ProviderAccount           = 'circuits/provider-accounts'
    ProviderNetwork           = 'circuits/provider-networks'

    # Core
    DataFile                  = 'core/data-files'
    DataSource                = 'core/data-sources'
    Job                       = 'core/jobs'
    ObjectType                = 'core/object-types'

    # DCIM
    Cable                     = 'dcim/cables'
    CableTermination          = 'dcim/cable-terminations'
    ConnectedDevice           = 'dcim/connected-device'
    ConsolePortTemplate       = 'dcim/console-port-templates'
    ConsolePort               = 'dcim/console-ports'
    ConsoleServerPortTemplate = 'dcim/console-server-port-templates'
    ConsoleServerPort         = 'dcim/console-server-ports'
    DevicebayTemplate         = 'dcim/device-bay-templates'
    Devicebay                 = 'dcim/device-bays'
    DeviceRole                = 'dcim/device-roles'
    DeviceType                = 'dcim/device-types'
    Device                    = 'dcim/devices'
    FrontPort                 = 'dcim/front-ports'
    FrontPortTemplate         = 'dcim/front-port-templates'
    InterfaceTemplate         = 'dcim/interface-templates'
    Interface                 = 'dcim/interfaces'
    InventoryItem             = 'dcim/inventory-items'
    InventoryItemRole         = 'dcim/inventory-item-roles'
    InventoryItemTemplate     = 'dcim/inventory-item-templates'
    Location                  = 'dcim/locations'
    Manufacturer              = 'dcim/manufacturers'
    ModuleBay                 = 'dcim/module-bays'
    ModuleBayTemplate         = 'dcim/module-bay-templates'
    Module                    = 'dcim/modules'
    ModuleType                = 'dcim/module-types'
    Platform                  = 'dcim/platforms'
    PowerFeed                 = 'dcim/power-feeds'
    PowerOutletTemplate       = 'dcim/power-outlet-templates'
    PowerOutlet               = 'dcim/power-outlets'
    PowerPanel                = 'dcim/power-panels'
    PowerPortTemplate         = 'dcim/power-port-templates'
    PowerPort                 = 'dcim/power-ports'
    RackReservation           = 'dcim/rack-reservations'
    RackRole                  = 'dcim/rack-roles'
    RackType                  = 'dcim/rack-types'
    Rack                      = 'dcim/racks'
    RearPort                  = 'dcim/rear-ports'
    RearPortTemplate          = 'dcim/rear-port-templates'
    Region                    = 'dcim/regions'
    SiteGroup                 = 'dcim/site-groups'
    Site                      = 'dcim/sites'
    VirtualChassis            = 'dcim/virtual-chassis'
    VirtualDeviceContext      = 'dcim/virtual-device-contexts'

    # Extras
    Bookmark                  = 'extras/bookmarks'
    ConfigContext             = 'extras/config-contexts'
    ConfigTemplate            = 'extras/config-templates'
    CustomFieldChoiceSet      = 'extras/custom-field-choice-sets'
    CustomField               = 'extras/custom-fields'
    CustomLink                = 'extras/custom-links'
    EventRule                 = 'extras/event-rules'
    ExportTemplate            = 'extras/export-templates'
    ImageAttachment           = 'extras/image-attachments'
    JournalEntry              = 'extras/journal-entries'
    ObjectChange              = 'extras/object-changes'
    SavedFilter               = 'extras/saved-filters'
    Script                    = 'extras/scripts'
    Tag                       = 'extras/tags'
    Webhook                   = 'extras/webhooks'

    # IPAM
    Aggregate                 = 'ipam/aggregates'
    Asn                       = 'ipam/asns'
    AsnRange                  = 'ipam/asn-ranges'
    FhrpGroup                 = 'ipam/fhrp-groups'
    FhrpGroupAssignment       = 'ipam/fhrp-group-assignments'
    IpAddress                 = 'ipam/ip-addresses'
    IpRange                   = 'ipam/ip-ranges'
    Prefix                    = 'ipam/prefixes'
    Rir                       = 'ipam/rirs'
    Role                      = 'ipam/roles'
    RouteTarget               = 'ipam/route-targets'
    Service                   = 'ipam/services'
    ServiceTemplate           = 'ipam/service-templates'
    VlanGroup                 = 'ipam/vlan-groups'
    VlanTranslationPolicy     = 'ipam/vlan-translation-policies'
    VlanTranslationRule       = 'ipam/vlan-translation-rules'
    Vlan                      = 'ipam/vlans'
    Vrf                       = 'ipam/vrfs'

    # Tenancy
    Contact                   = 'tenancy/contacts'
    ContactAssignment         = 'tenancy/contact-assignments'
    ContactGroup              = 'tenancy/contact-groups'
    ContactRole               = 'tenancy/contact-roles'
    TenantGroup               = 'tenancy/tenant-groups'
    Tenant                    = 'tenancy/tenants'

    # Users
    User                      = 'users/users'
    UserGroup                 = 'users/groups'
    UserToken                 = 'users/tokens'
    Permission                = 'users/permissions'

    # Virtualization
    ClusterGroup              = 'virtualization/cluster-groups'
    ClusterType               = 'virtualization/cluster-types'
    Cluster                   = 'virtualization/clusters'
    VMInterface               = 'virtualization/interfaces'
    VirtualDisk               = 'virtualization/virtual-disks'
    VirtualMachine            = 'virtualization/virtual-machines'

    # VPN
    IkePolicy                 = 'vpn/ike-policies'
    IkeProposal               = 'vpn/ike-proposals'
    IpsecPolicy               = 'vpn/ipsec-policies'
    IpsecProfile              = 'vpn/ipsec-profiles'
    IpsecProposal             = 'vpn/ipsec-proposals'
    L2vpn                     = 'vpn/l2vpns'
    L2vpnTermination          = 'vpn/l2vpn-terminations'
    Tunnel                    = 'vpn/tunnels'
    TunnelGroup               = 'vpn/tunnel-groups'
    TunnelTermination         = 'vpn/tunnel-terminations'

    # Wireless
    WirelessLan               = 'wireless/wireless-lans'
    WirelessLanGroup          = 'wireless/wireless-lan-groups'
    WirelessLink              = 'wireless/wireless-links'
}
