version: 1.{build}.{branch}
install:
- ps: Install-Module -Name InvokeBuild -RequiredVersion 5.4.1
- ps: Install-Module -Name PSScriptAnalyzer -RequiredVersion 1.16.1
- ps: Install-Module -Name Pester -RequiredVersion 4.3.1
- ps: Install-Module -Name PlatyPS -RequiredVersion 0.9.0
- ps: #Generalize environment variables to allow build to more readily run in other build systems
- ps: $ENV:COMMIT_MESSAGE = $ENV:APPVEYOR_REPO_COMMIT_MESSAGE + "`n" + $ENV:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED
- ps: $ENV:manifest = Test-ModuleManifest -Path .\module\powerbox.psd1
- ps: $ENV:repo_version = IF ($ENV:APPVEYOR_REPO_TAG_NAME){$ENV:APPVEYOR_REPO_TAG_NAME} else {$ENV:manifest.version}
- ps: $ENV:REPO_TAG = $ENV:APPVEYOR_REPO_TAG
- ps: if ($ENV:REPO_TAG) { Write-Host "Publishing version $($ENV:repo_version)" -foregroundcolor Magenta}
- ps: Invoke-Build -task bumpversion
- ps: Update-AppveyorBuild -Version $ENV:repo_version -

environment:
  nuget_api_key:
    secure: TVDL0yRh7Mq8p85ZHiK1/bnBhxCfnKFogJqtuPKY39zJAzRUf8fHYTdVxbAbOEGU
  access_token:
    secure: aT1eVpfAKwN03D9Lx+W6uPuotoW2gOqEisBtTpnrZx5rf1A54XztZTw+NbcA6lqQ

build_script:
- ps: invoke-build
after_build:
- ps: Compress-Archive -Path .\Release\powerbox -destination .\powerbox.zip
- ps: Push-AppveyorArtifact .\powerbox.zip -FileName powerbox.zip

test_script:
- ps: invoke-build -task test
after_test:
- ps: |
     $wc = New-Object 'System.Net.WebClient'
     $wc.uploadfile("https://ci.appveyor.com/api/testresults/nunit3/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\testresult.xml))

before_deploy:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "batmanama@outlook.com"
  - git config --global user.name "build"
deploy_script:
- ps: invoke-build -task publish
