version: 1.0.{build}
install:
- ps: Install-Module -Name InvokeBuild -RequiredVersion 5.4.1
- ps: Install-Module -Name PSScriptAnalyzer -RequiredVersion 1.16.1
- ps: Install-Module -Name Pester -RequiredVersion 4.3.1
- ps: Install-Module -Name PlatyPS -RequiredVersion 0.9.0
- ps: $ENV:COMMIT_MESSAGE = $ENV:APPVEYOR_REPO_COMMIT_MESSAGE + "`n" + $ENV:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED
- ps: $ENV:repo_version = IF ($ENV:APPVEYOR_REPO_TAG_NAME){$ENV:APPVEYOR_REPO_TAG_NAME} else {$ENV:APPVEYOR_BUILD_VERSIO}
- ps: $ENV:REPO_TAG = $ENV:APPVEYOR_REPO_TAG

environment:
  nuget_api_key:
    secure: TVDL0yRh7Mq8p85ZHiK1/bnBhxCfnKFogJqtuPKY39zJAzRUf8fHYTdVxbAbOEGU
  access_token:
    secure: aT1eVpfAKwN03D9Lx+W6uPuotoW2gOqEisBtTpnrZx5rf1A54XztZTw+NbcA6lqQ

build_script:
- ps: invoke-build
test_script:
- ps: invoke-build -task test
deploy_script:
- ps: invoke-build -task publish
before_deploy:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "batmanama@outlook.com"
  - git config --global user.name "build"
